version: "3.9"
services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    container_name: demo_credit_db
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 10s
      retries: 5

  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: demo_credit
    ports:
      - "80:80"
    env_file:
      - .env
    environment:
      - NODE_ENV=production # Set to production
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
